/*
 * File: app/store/ListStore.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Theme.store.ListStore', {
    extend: 'Ext.data.Store',

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            groupField: 'group',
            storeId: 'ListStore',
            data: [
                {
                    group: 'Champagne & Sparkling Wine',
                    name: 'Prosecco Casa Burti',
                    price: '$ 35',
                    size: '75 CL'
                },
                {
                    group: 'Champagne & Sparkling Wine',
                    name: 'Veuve Cliquot Brut',
                    price: '$ 82',
                    size: '75 CL'
                },
                {
                    group: 'Wine',
                    name: 'Lillet, blanc',
                    price: '$ 8',
                    size: '6 CL'
                },
                {
                    group: 'Wine',
                    name: 'Lillet, rouge',
                    price: '$ 8',
                    size: '6 CL'
                },
                {
                    group: 'Fortified Wine',
                    name: 'Bodegas Williams & Humbert',
                    price: '$ 11',
                    size: '6 CL',
                    desc: 'Collection Fino, sherry'
                },
                {
                    group: 'Fortified Wine',
                    name: 'Bodegas Williams & Humbert',
                    price: '$ 15',
                    size: '6 CL',
                    desc: 'Collection Olorosso, sherry, 12 Yrs'
                }
            ]
        }, cfg)]);
    }
});