/*
 * File: app/view/MyList.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Theme.view.MyList', {
    extend: 'Ext.dataview.List',
    alias: 'widget.mylist',

    requires: [
        'Theme.view.MyListViewModel',
        'Ext.XTemplate',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Spacer',
        'Ext.Label'
    ],

    viewModel: {
        type: 'mylist'
    },
    cls: 'flex-items',
    disableSelection: true,
    itemTpl: [
        '<div class="flex">',
        '    <div style="flex: 1;">{name}</div> ',
        '    <div>{size}</div> ',
        '    <div>{price}</div>',
        '    <div class="btn">ADD</div>',
        '</div>',
        '<div class="desc">{desc}</div>'
    ],
    store: 'ListStore',
    grouped: true,
    groupHeader: {
        xtype: 'itemheader',
        tpl: '{html}'
    },

    items: [
        {
            xtype: 'toolbar',
            docked: 'top',
            title: 'TORSHAVN',
            items: [
                {
                    xtype: 'button',
                    ui: 'plain',
                    iconCls: 'x-fa fa-bars',
                    text: ''
                },
                {
                    xtype: 'spacer'
                },
                {
                    xtype: 'button',
                    ui: 'plain',
                    iconCls: 'x-fa fa-search',
                    text: ''
                }
            ]
        },
        {
            xtype: 'container',
            cls: 'header',
            docked: 'top',
            html: 'Champagne, Wine, Vermouth&nbsp;Fortified&nbsp;Wines',
            layout: {
                type: 'vbox',
                pack: 'center'
            }
        },
        {
            xtype: 'container',
            cls: 'panel-pull',
            docked: 'bottom',
            layout: {
                type: 'hbox',
                align: 'center',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'button',
                    ui: 'round',
                    iconCls: 'x-fa fa-chevron-up',
                    text: ''
                },
                {
                    xtype: 'label',
                    cls: 'text',
                    html: 'PULL UP FOR DETAILS'
                },
                {
                    xtype: 'spacer'
                },
                {
                    xtype: 'label',
                    cls: 'text',
                    html: '<i class="fa fa-glass"></i>x2 $45'
                },
                {
                    xtype: 'spacer'
                },
                {
                    xtype: 'button',
                    text: 'Confirm Order'
                }
            ]
        }
    ]

});